mxnet_variant_str:
  - cu102
  - cpu
mxnet_variant_version:
  #  - 0.0.10
  #  - 0.0.20
  - 0.0.30
  - 0.0.40
mxnet_version:
  - 1.8.0
cudatoolkit_version:
  - 10.2
cudnn_version:
  - 8.1
python_version:
  - 3.8
nccl_version:
  - 2.9
libopencv:  # [win]
  - 3.4.1   # [win]
zip_keys:
  - mxnet_variant_str
  - mxnet_variant_version
