mxnet_variant_str:
  - cpu
  - cu102
mxnet_variant_version:
  - 0.0.20
  - 0.0.30
mxnet_version:
  - 1.8.0
c_compiler:             # [linux]
  - gcc                 # [linux]
cxx_compiler:           # [linux]
  - gxx                 # [linux]
c_compiler_version:     # [linux]
  - 7                   # [linux]
cxx_compiler_version:   # [linux]
  - 7                   # [linux]
c_compiler_version:     # [osx]
  - 10                  # [osx]
cxx_compiler_version:   # [osx]
  - 10                  # [osx]
cudatoolkit_version:
  - 10.2
cuda_compiler_version:
  - 10.2
cudnn_version:
  - 8.1
nccl_version:
  - 2.9
libopencv:  # [win]
  - 3.4.1   # [win]
zip_keys:
  - mxnet_variant_str
  - mxnet_variant_version
